//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskList
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskId { get; set; }
        public string Task1 { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public int Priority { get; set; }
    
        public virtual Priority Priority1 { get; set; }
    }
}
